# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"
    config.ssh.insert_key = true

    config.vm.provider :virtualbox do |v|
        v.name = "displays"
        v.memory = 2048
        v.cpus = 2
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.hostname = "displays"
    config.vm.network :private_network, ip: "192.168.33.100"

    config.vm.provision :hostmanager

    # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
    config.vm.define :displays do |displays|
    end

    # First, install python
    config.vm.provision "shell" do |s|
      s.inline = "apt-get install -y python && apt-get install -y python-pip"
    end

end
